✨ Admin | RBAC for Staff and Admin Users
SSWConsulting/SSW.Rewards.Mobile pull request #694
Opened 2024-02-19 05:54 UTC by tkapa

> 1. What triggered this change? (PBI link, Email Subject, conversation + reason, etc)

✏️ We currently have some pages that restrict functionality only to Admin users. However, all pages are visible to users regardless of their roles, even if they aren't Staff or Admin!

> 2. What was changed?

✏️ 

> 3. Did you do pair or mob programming?

✏️

2024-02-20 23:39 UTC, matt-goldman requested changes
Love your work! Thoughts on restricting quizzes to admin?

2024-02-20 23:39 UTC, matt-goldman commented on src/AdminUI/Pages/Quizzes.razor
Can we keep this at just admin for now? Otherwise people will be able to view the benchmark answers.

2024-02-20 23:39 UTC, matt-goldman commented on src/AdminUI/Shared/NavMenu.razor
As above - I think we should restrict quizzes to admin

2024-02-21 01:24 UTC, tkapa commented on src/AdminUI/Pages/Quizzes.razor
Agreed :) 

I've pushed an update

2024-02-21 01:24 UTC, tkapa commented on src/AdminUI/Shared/NavMenu.razor
Done - see above

2024-02-21 03:27 UTC, merged