Mobile | Fix the answer field for quizzes
SSWConsulting/SSW.Rewards.Mobile pull request #710
Opened 2024-02-23 07:45 UTC by AntPolkanov

> 1. What triggered this change? (PBI link, Email Subject, conversation + reason, etc)

✏️ The input box for quizzes was single line

> 2. What was changed?

✏️ The input box is now multiline. 
The cursor color is Red. 
The keyboard hides when the user clicks outside of it on the PeoplePage.
Upgraded MAUI to the latest version

> 3. Did you do pair or mob programming?

✏️ No

2024-02-23 22:55 UTC, matt-goldman requested changes
Looks good, although please use an event to command behavior (there's one ready-rolled in the MAUI Community Toolkit, which I think we're already using elsewhere) instead of event handlers.

2024-02-23 22:55 UTC, matt-goldman commented on src/MobileUI/Pages/EarnDetailsPage.xaml.cs
We shoud use `EventToCommandBehavior` for this.

2024-02-23 22:55 UTC, matt-goldman commented on src/MobileUI/ViewModels/EarnDetailsViewModel.cs
We should update all the `ICommand` instances to use `[RelayCommand]` from the MVVM CommnunityToolkit. @zacharykeeping already did this for the `ObservableProperty` instances.

See: https://github.com/SSWConsulting/SSW.Rewards.Mobile/issues/711

(You can mark this as closed - not blocking this PR on this comment)

2024-02-25 23:29 UTC, AntPolkanov commented on src/MobileUI/ViewModels/EarnDetailsViewModel.cs
Done

2024-02-25 23:29 UTC, AntPolkanov commented on src/MobileUI/Pages/EarnDetailsPage.xaml.cs
Done

2024-02-26 03:08 UTC, matt-goldman approved these changes
🚀 LGTM - I think we should review whether that handler should be in `MauiProgram` (I don't they generally should be, although this one might be alright as it solves a problem). I think we have other handlers in other places. I've added this issue for that: https://github.com/SSWConsulting/SSW.Rewards.Mobile/issues/713

2024-02-26 03:12 UTC, merged