✨ Mobile | Activity page v2024
SSWConsulting/SSW.Rewards.Mobile pull request #822
Opened 2024-04-05 06:34 UTC by zacharykeeping

> 1. What triggered this change? (PBI link, Email Subject, conversation + reason, etc)

✏️ 

> 2. What was changed?

✏️ 

> 3. Did you do pair or mob programming?

✏️

2024-04-07 23:54 UTC, matt-goldman requested changes
Awesome work. I've noticed a few things that I think need some attention.

2024-04-07 23:54 UTC, matt-goldman commented on src/Common/DTOs/ActivityFeed/ActivityFeedViewModel.cs
Please address the warnings in this file. We've been relaxed with warnings in existing code, but I don't want to introduce more.

2024-04-07 23:54 UTC, matt-goldman commented on src/MobileUI/Services/ActivityService.cs
This service and abstraction should be removed:

1. The error handling should be done in the ViewModel
2. This demonstrates the lazy class code smell

2024-04-07 23:54 UTC, matt-goldman commented on src/Common/DTOs/ActivityFeed/ActivityFeedViewModel.cs
I think we should be consistent with naming. I think this should be named something like `ActivityFeedItemDto` (or something along those lines). We are typically using [...]ViewModel to represent a view, so I would expect this to contain a collection of `ActivityFeedItemDto` (or whatever it gets called) and some metadata.

2024-04-08 04:31 UTC, zacharykeeping commented on src/Common/DTOs/ActivityFeed/ActivityFeedViewModel.cs
Done - the warnings have been addressed.

2024-04-08 04:31 UTC, zacharykeeping commented on src/MobileUI/Services/ActivityService.cs
Done - this has been removed.

2024-04-08 04:32 UTC, zacharykeeping commented on src/Common/DTOs/ActivityFeed/ActivityFeedViewModel.cs
Done - the naming for this has been improved.

2024-04-08 05:47 UTC, matt-goldman approved these changes
LGTM 🚀 🚢 😎

2024-04-08 05:51 UTC, merged